const sampleDataBang = {
2: [
  { name: "Peninsular Gneiss", about: "Peninsular Gneiss Complex are the gneissic complex of the metamorphics found all over the Indian Peninsula, on top of which, the supra-crustal Dharwar System have been laid down.", timeSpent: "1 hours", imageUrl: "PG.png", linkUrl: "https://www.google.com/search?q=Peninsular+Gneiss&rlz=1C1ONGR_enIN1061IN1061&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/place/Peninsular+Gneiss/@12.9486707,77.5869644,17z/data=!3m1!4b1!4m6!3m5!1s0x3bae15c141740d2f:0x2b01a569464aebf6!8m2!3d12.9486707!4d77.5895393!16s%2Fm%2F05mrr35?entry=ttu" }
],

3: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
],

4: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Avenue Road", about: "Avenue Road is a busy shopping and commercial street in Bangalore, the state capital of Karnataka, India. It is located in Chickpet and runs through the heart of the city. It also connects the Mysore Road and K G Road in the city. It is in close proximity to Majestic bus station and Bangalore City Railway station. ", timeSpent: "1 hours", imageUrl: "avenue_road.png",linkUrl: "https://www.google.com/search?q=Avenue+Road&rlz=1C1ONGR_enIN1061IN1061&sourceid=chrome&ie=UTF-8", mapURL: "https://www.google.com/maps/place/Avenue+Rd,+Bengaluru,+Karnataka/@12.968609,77.5764651,17z/data=!3m1!4b1!4m6!3m5!1s0x3bae1609875f1335:0x2e9aa8b49e493f49!8m2!3d12.968609!4d77.57904!16s%2Fm%2F0n5351b?entry=ttu" }
],

5: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" }
],

6: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Government Musuem", about: "Government Museum, Bangalore, established in 1865 by the Mysore State with the guidance of Surgeon Edward Balfour who founded the museum in Madras and supported by the Chief Commissioner of Mysore, L.B. Bowring, is one of the oldest museums in India and the second oldest museum in South India.", timeSpent: "1 hours", imageUrl: "govtMuseum.png", linkUrl: "https://www.tripadvisor.com/Attraction_Review-g297596-d2651189-Reviews-or10-Government_Museum_and_Art_Gallery-Chandigarh.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=government+museum+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

7: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

8: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Government Musuem", about: "Government Museum, Bangalore, established in 1865 by the Mysore State with the guidance of Surgeon Edward Balfour who founded the museum in Madras and supported by the Chief Commissioner of Mysore, L.B. Bowring, is one of the oldest museums in India and the second oldest museum in South India.", timeSpent: "1 hours", imageUrl: "govtMuseum.png", linkUrl: "https://www.tripadvisor.com/Attraction_Review-g297596-d2651189-Reviews-or10-Government_Museum_and_Art_Gallery-Chandigarh.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=government+museum+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

9: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "JC Road", about: "Jayachamarajendra Road, or simply J.C. Road, is a street in the heart of Bangalore, the state capital of Karnataka, India, named after Maharaja Jayachamaraja Wadiyar. It is located in Kalasipalya and connects with Kasturba Road to the north.", timeSpent: "2 hours", imageUrl: "jcRoad.png", linkUrl: "https://www.google.com/search?q=jc+road%2C+bangalore&sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&sxsrf=ADLYWIJN-ON30iOb6-NaU3zl4KVtdv803g%3A1715105541771&ei=BW86ZoHRLqLh4-EPqKe_sA8&ved=0ahUKEwjB58aEkvyFAxWi8DgGHajTD_YQ4dUDCBE&uact=5&oq=jc+road%2C+bangalore&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmpjIHJvYWQsIGJhbmdhbG9yZTIKECMYgAQYJxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyBRAAGIAEMgoQABiABBhDGIoFMgUQABiABDIKEAAYgAQYQxiKBUi-IlC6GViXHnABeAGQAQCYAaQBoAGSBqoBAzAuNbgBA8gBAPgBAZgCA6ACyQLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYyAMYigUYrwHYAQHCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIGEAAYFhgemAMAiAYBkAYUugYGCAEQARgIkgcDMS4yoAenKA&sclient=gws-wiz-serp", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=jc+road+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

10: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "JC Road", about: "Jayachamarajendra Road, or simply J.C. Road, is a street in the heart of Bangalore, the state capital of Karnataka, India, named after Maharaja Jayachamaraja Wadiyar. It is located in Kalasipalya and connects with Kasturba Road to the north.", timeSpent: "2 hours", imageUrl: "jcRoad.png", linkUrl: "https://www.google.com/search?q=jc+road%2C+bangalore&sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&sxsrf=ADLYWIJN-ON30iOb6-NaU3zl4KVtdv803g%3A1715105541771&ei=BW86ZoHRLqLh4-EPqKe_sA8&ved=0ahUKEwjB58aEkvyFAxWi8DgGHajTD_YQ4dUDCBE&uact=5&oq=jc+road%2C+bangalore&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmpjIHJvYWQsIGJhbmdhbG9yZTIKECMYgAQYJxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyBRAAGIAEMgoQABiABBhDGIoFMgUQABiABDIKEAAYgAQYQxiKBUi-IlC6GViXHnABeAGQAQCYAaQBoAGSBqoBAzAuNbgBA8gBAPgBAZgCA6ACyQLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYyAMYigUYrwHYAQHCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIGEAAYFhgemAMAiAYBkAYUugYGCAEQARgIkgcDMS4yoAenKA&sclient=gws-wiz-serp", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=jc+road+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Lal Bagh", about: "Lalbagh Botanical Garden or simply Lalbagh, is an botanical garden in Bangalore, India, with an over 200-year history. First planned and laid out during the dalavaiship of Hyder Ali, the garden was later managed under numerous British Superintendents before Indian Independence.", timeSpent: "1 hours", imageUrl: "lal_bagh.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d631367-Reviews-Lalbagh_Botanical_Garden-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Lalbagh+Botanical+Garden/@12.947703,77.5807387,16z/data=!4m10!1m2!2m1!1slal+bagh+bangalore!3m6!1s0x3bae15c191f2d31d:0x8e110b99df2fbe22!8m2!3d12.9494158!4d77.5846805!15sChJsYWwgYmFnaCBiYW5nYWxvcmVaFCISbGFsIGJhZ2ggYmFuZ2Fsb3JlkgEQYm90YW5pY2FsX2dhcmRlbuABAA!16zL20vMDUxd3A0?entry=ttu" }
],

11: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "JC Road", about: "Jayachamarajendra Road, or simply J.C. Road, is a street in the heart of Bangalore, the state capital of Karnataka, India, named after Maharaja Jayachamaraja Wadiyar. It is located in Kalasipalya and connects with Kasturba Road to the north.", timeSpent: "2 hours", imageUrl: "jcRoad.png", linkUrl: "https://www.google.com/search?q=jc+road%2C+bangalore&sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&sxsrf=ADLYWIJN-ON30iOb6-NaU3zl4KVtdv803g%3A1715105541771&ei=BW86ZoHRLqLh4-EPqKe_sA8&ved=0ahUKEwjB58aEkvyFAxWi8DgGHajTD_YQ4dUDCBE&uact=5&oq=jc+road%2C+bangalore&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmpjIHJvYWQsIGJhbmdhbG9yZTIKECMYgAQYJxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyBRAAGIAEMgoQABiABBhDGIoFMgUQABiABDIKEAAYgAQYQxiKBUi-IlC6GViXHnABeAGQAQCYAaQBoAGSBqoBAzAuNbgBA8gBAPgBAZgCA6ACyQLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYyAMYigUYrwHYAQHCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIGEAAYFhgemAMAiAYBkAYUugYGCAEQARgIkgcDMS4yoAenKA&sclient=gws-wiz-serp", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=jc+road+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Gandhi Bazar", about: "Gandhi Bazaar is a busy market area in Basavanagudi, Bangalore, known mainly for its flower and condiment hawker shops. One of the oldest areas in the city, Gandhi Bazaar is said to be traditional and conservative.", timeSpent: "1 hours", imageUrl: "gandhiMarket.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d4401019-Reviews-Gandhi_Bazaar-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=gandhi+bazaar+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

12: [
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "2 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "JC Road", about: "Jayachamarajendra Road, or simply J.C. Road, is a street in the heart of Bangalore, the state capital of Karnataka, India, named after Maharaja Jayachamaraja Wadiyar. It is located in Kalasipalya and connects with Kasturba Road to the north.", timeSpent: "2 hours", imageUrl: "jcRoad.png", linkUrl: "https://www.google.com/search?q=jc+road%2C+bangalore&sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&sxsrf=ADLYWIJN-ON30iOb6-NaU3zl4KVtdv803g%3A1715105541771&ei=BW86ZoHRLqLh4-EPqKe_sA8&ved=0ahUKEwjB58aEkvyFAxWi8DgGHajTD_YQ4dUDCBE&uact=5&oq=jc+road%2C+bangalore&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmpjIHJvYWQsIGJhbmdhbG9yZTIKECMYgAQYJxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyBRAAGIAEMgoQABiABBhDGIoFMgUQABiABDIKEAAYgAQYQxiKBUi-IlC6GViXHnABeAGQAQCYAaQBoAGSBqoBAzAuNbgBA8gBAPgBAZgCA6ACyQLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYyAMYigUYrwHYAQHCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIGEAAYFhgemAMAiAYBkAYUugYGCAEQARgIkgcDMS4yoAenKA&sclient=gws-wiz-serp", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=jc+road+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Gandhi Bazar", about: "Gandhi Bazaar is a busy market area in Basavanagudi, Bangalore, known mainly for its flower and condiment hawker shops. One of the oldest areas in the city, Gandhi Bazaar is said to be traditional and conservative.", timeSpent: "1 hours", imageUrl: "gandhiMarket.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d4401019-Reviews-Gandhi_Bazaar-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=gandhi+bazaar+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Bugle Rock", about: "Bugle Rock is a massive rock in the Basavanagudi area of South Bangalore, in the state of Karnataka. It is an abrupt rise above the ground of peninsular gneiss as the main rock formation and with an assessed age of about 3,000 million years. Bugle Rock has generated wide interest among the scientific community. ", timeSpent: "2 hours", imageUrl: "bugle_rock.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d4401091-Reviews-Bugle_Rock-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&biw=767&bih=695&output=search&q=Bugle+Rock&si=ACC90nwet1eSy3BcbbysqB4SsCuPQntNcJ_HJTyRHPZE3pim1cKY65eBvAMzM8N8xYzkeOwq9vYYtMM4PA81P-bJAWmTX5XTHoVBj24nwRw4QS5sl55mKqvY3sBzUpQMiUQwdGE2jQRi9pQVGiccmFUI8wqq_ounx8G9oZT7T9eFfWl2j73rHpI0E3jNfLCkhucj3kCu-_232pxwzgvxqOR2WLlqcNcwGquCXWrh2w2L8jEFYBN145FLpGx9mV_-gkM_Z1VCX3b0X2a2X3o4QF4-r4GoBWongQ%3D%3D&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

 13 : [
  { name: "Peninsular Gneiss", about: "Peninsular Gneiss Complex are the gneissic complex of the metamorphics found all over the Indian Peninsula, on top of which, the supra-crustal Dharwar System have been laid down.", timeSpent: "1 hours", imageUrl: "PG.png", linkUrl: "https://www.google.com/search?q=Peninsular+Gneiss&rlz=1C1ONGR_enIN1061IN1061&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/place/Peninsular+Gneiss/@12.9486707,77.5869644,17z/data=!3m1!4b1!4m6!3m5!1s0x3bae15c141740d2f:0x2b01a569464aebf6!8m2!3d12.9486707!4d77.5895393!16s%2Fm%2F05mrr35?entry=ttu" },
  { name: "Savandurga", about: "Savandurga is a hill 60 km west of Bengaluru, off the Magadi road in India. It is the largest monolith hills in Asia. The hill rises to 1226 m above mean sea level and forms a part of the Deccan plateau. It consists of peninsular gneiss, granites, basic dykes, and laterites.", timeSpent: "2 hours", imageUrl: "Savandurga.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g7983256-d1204347-Reviews-Savandurga-Dabguli_Ramanagara_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=savandurga&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Avenue Road", about: "Avenue Road is a busy shopping and commercial street in Bangalore, the state capital of Karnataka, India. It is located in Chickpet and runs through the heart of the city. It also connects the Mysore Road and K G Road in the city. It is in close proximity to Majestic bus station and Bangalore City Railway station. ", timeSpent: "3 hours", imageUrl: "avenue_road.png",linkUrl: "https://www.google.com/search?q=Avenue+Road&rlz=1C1ONGR_enIN1061IN1061&sourceid=chrome&ie=UTF-8", mapURL: "https://www.google.com/maps/place/Avenue+Rd,+Bengaluru,+Karnataka/@12.968609,77.5764651,17z/data=!3m1!4b1!4m6!3m5!1s0x3bae1609875f1335:0x2e9aa8b49e493f49!8m2!3d12.968609!4d77.57904!16s%2Fm%2F0n5351b?entry=ttu" },
  { name: "Banglore Aquarium", about: "Bangalore Aquarium, also known as Government Aquarium, is the second largest aquarium in India. It is located at the entrance of Cubbon Park in Bangalore, India, and was established in 1983. It has a variety of exotic cultivable as well as ornamental fish on display. It is very near to vishweshwarayya museum.", timeSpent: "3 hours", imageUrl: "banglore_aquarium.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d3913104-Reviews-Bangalore_Aquarium-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Government+Aquarium/@12.9965596,77.5817207,13z/data=!4m10!1m2!2m1!1sbangalore+aquarium!3m6!1s0x3bae1670e0047449:0x3e614ea1bba4e8c9!8m2!3d12.9765148!4d77.5985397!15sChJiYW5nYWxvcmUgYXF1YXJpdW1aFCISYmFuZ2Fsb3JlIGFxdWFyaXVtkgEIYXF1YXJpdW3gAQA!16s%2Fm%2F09gmfl2?entry=ttu" },
  { name: "Government Musuem", about: "Government Museum, Bangalore, established in 1865 by the Mysore State with the guidance of Surgeon Edward Balfour who founded the museum in Madras and supported by the Chief Commissioner of Mysore, L.B. Bowring, is one of the oldest museums in India and the second oldest museum in South India.", timeSpent: "3 hours", imageUrl: "govtMuseum.png", linkUrl: "https://www.tripadvisor.com/Attraction_Review-g297596-d2651189-Reviews-or10-Government_Museum_and_Art_Gallery-Chandigarh.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=government+museum+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Nrityagram", about: "Nrityagram is India's first modern Gurukul for Indian classical dances and an intentional community in the form of a dance village, set up by Odissi dancer Protima Gauri in 1990.", timeSpent: "3 hours", imageUrl: "nrit.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d2587730-Reviews-Nrityagram_Tour-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=nrityagram+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "JC Road", about: "Jayachamarajendra Road, or simply J.C. Road, is a street in the heart of Bangalore, the state capital of Karnataka, India, named after Maharaja Jayachamaraja Wadiyar. It is located in Kalasipalya and connects with Kasturba Road to the north.", timeSpent: "3 hours", imageUrl: "jcRoad.png", linkUrl: "https://www.google.com/search?q=jc+road%2C+bangalore&sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&sxsrf=ADLYWIJN-ON30iOb6-NaU3zl4KVtdv803g%3A1715105541771&ei=BW86ZoHRLqLh4-EPqKe_sA8&ved=0ahUKEwjB58aEkvyFAxWi8DgGHajTD_YQ4dUDCBE&uact=5&oq=jc+road%2C+bangalore&gs_lp=Egxnd3Mtd2l6LXNlcnAiEmpjIHJvYWQsIGJhbmdhbG9yZTIKECMYgAQYJxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIKEAAYgAQYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyBRAAGIAEMgoQABiABBhDGIoFMgUQABiABDIKEAAYgAQYQxiKBUi-IlC6GViXHnABeAGQAQCYAaQBoAGSBqoBAzAuNbgBA8gBAPgBAZgCA6ACyQLCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICGRAuGIAEGLADGEMYxwEYyAMYigUYrwHYAQHCAhMQLhiABBiwAxhDGMgDGIoF2AEBwgIGEAAYFhgemAMAiAYBkAYUugYGCAEQARgIkgcDMS4yoAenKA&sclient=gws-wiz-serp", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=jc+road+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Lal Bagh", about: "Lalbagh Botanical Garden or simply Lalbagh, is an botanical garden in Bangalore, India, with an over 200-year history. First planned and laid out during the dalavaiship of Hyder Ali, the garden was later managed under numerous British Superintendents before Indian Independence.", timeSpent: "3 hours", imageUrl: "lal_bagh.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d631367-Reviews-Lalbagh_Botanical_Garden-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps/place/Lalbagh+Botanical+Garden/@12.947703,77.5807387,16z/data=!4m10!1m2!2m1!1slal+bagh+bangalore!3m6!1s0x3bae15c191f2d31d:0x8e110b99df2fbe22!8m2!3d12.9494158!4d77.5846805!15sChJsYWwgYmFnaCBiYW5nYWxvcmVaFCISbGFsIGJhZ2ggYmFuZ2Fsb3JlkgEQYm90YW5pY2FsX2dhcmRlbuABAA!16zL20vMDUxd3A0?entry=ttu" },
  { name: "Gandhi Bazar", about: "Gandhi Bazaar is a busy market area in Basavanagudi, Bangalore, known mainly for its flower and condiment hawker shops. One of the oldest areas in the city, Gandhi Bazaar is said to be traditional and conservative.", timeSpent: "3 hours", imageUrl: "gandhiMarket.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d4401019-Reviews-Gandhi_Bazaar-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&output=search&q=gandhi+bazaar+bangalore&source=lnms&entry=mc&ved=1t:200715&ictx=111" },
  { name: "Bugle Rock", about: "Bugle Rock is a massive rock in the Basavanagudi area of South Bangalore, in the state of Karnataka. It is an abrupt rise above the ground of peninsular gneiss as the main rock formation and with an assessed age of about 3,000 million years. Bugle Rock has generated wide interest among the scientific community. ", timeSpent: "3 hours", imageUrl: "bugle_rock.png",linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297628-d4401091-Reviews-Bugle_Rock-Bengaluru_Bangalore_District_Karnataka.html", mapURL: "https://www.google.com/maps?sca_esv=4d50ecf86976fd48&rlz=1C1ONGR_enIN1061IN1061&biw=767&bih=695&output=search&q=Bugle+Rock&si=ACC90nwet1eSy3BcbbysqB4SsCuPQntNcJ_HJTyRHPZE3pim1cKY65eBvAMzM8N8xYzkeOwq9vYYtMM4PA81P-bJAWmTX5XTHoVBj24nwRw4QS5sl55mKqvY3sBzUpQMiUQwdGE2jQRi9pQVGiccmFUI8wqq_ounx8G9oZT7T9eFfWl2j73rHpI0E3jNfLCkhucj3kCu-_232pxwzgvxqOR2WLlqcNcwGquCXWrh2w2L8jEFYBN145FLpGx9mV_-gkM_Z1VCX3b0X2a2X3o4QF4-r4GoBWongQ%3D%3D&source=lnms&entry=mc&ved=1t:200715&ictx=111" }
],

};

const sampleDataChand = {
  2: [
    { name: "Sukhna Lake", about: "Sukhna Lake in Chandigarh, India, is a reservoir at the foothills of the Himalayas. This 3 km² rain fed lake was created in 1958 by damming the Sukhna Choe, a seasonal stream coming down from the Shivalik Hills. Originally, the seasonal flow entered the lake directly, causing heavy siltation.", timeSpent: "1 hours", imageUrl: "sukhnaLake.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d1204434-Reviews-Sukhna_Lake-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Sukhna+Lake/@30.7420736,76.8008578,14z/data=!3m1!4b1!4m6!3m5!1s0x390fed34138d9147:0x8a7a0db7c410d5a2!8m2!3d30.7421379!4d76.8187557!16zL20vMDd6ZmM3?entry=ttu" }
  ],
  3: [
    { name: "Secretariat Building ", about: "A part of the capitol complex, this monument is the largest and tallest of the all the three edifices. Shaped like a concrete-slab, the Secretariat is eight storeys tall. It was built during 1953-59 and has the distinctive brise-soleil-louvered screen of deeply sculptured two-storey porticos in the centre.", timeSpent: "1 hours", imageUrl: "secBuilding.png", linkUrl: "https://www.google.com/search?q=Secretariat+Building%2C+Chandigarh&rlz=1C1ONGR_enIN1061IN1061&oq=secre&gs_lcrp=EgZjaHJvbWUqCAgDEEUYJxg7MgYIABBFGDkyBggBEEUYQDIICAIQRRgnGDsyCAgDEEUYJxg7MhUIBBAuGEMYrwEYxwEYgAQYigUYmAUyCggFEC4YsQMYgAQyCggGEAAYsQMYgAQyDAgHEAAYFBiHAhiABNIBCDM5OTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/search/Secretariat+Building,+Chandigarh/@30.7487379,76.7705976,14z/data=!3m1!4b1?entry=ttu" }
  ],
  4: [
    { name: "Secretariat Building ", about: "A part of the capitol complex, this monument is the largest and tallest of the all the three edifices. Shaped like a concrete-slab, the Secretariat is eight storeys tall. It was built during 1953-59 and has the distinctive brise-soleil-louvered screen of deeply sculptured two-storey porticos in the centre.", timeSpent: "1 hours", imageUrl: "secBuilding.png", linkUrl: "https://www.google.com/search?q=Secretariat+Building%2C+Chandigarh&rlz=1C1ONGR_enIN1061IN1061&oq=secre&gs_lcrp=EgZjaHJvbWUqCAgDEEUYJxg7MgYIABBFGDkyBggBEEUYQDIICAIQRRgnGDsyCAgDEEUYJxg7MhUIBBAuGEMYrwEYxwEYgAQYigUYmAUyCggFEC4YsQMYgAQyCggGEAAYsQMYgAQyDAgHEAAYFBiHAhiABNIBCDM5OTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/search/Secretariat+Building,+Chandigarh/@30.7487379,76.7705976,14z/data=!3m1!4b1?entry=ttu" },
    { name: "Tagore Theatre ", about: "Tagore Theatre, Chandigarh is a center for cultural performances located in Sector 18, Chandigarh. It was designed by architect Aditya Prakash, who was part of Chandigarh Capital Project Team, headed by Le Corbusier. Aditya Prakash was the principal of Chandigarh College of Architecture", timeSpent: "2 hours", imageUrl: "tagoreTheatre.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d13576385-Reviews-Tagore_Theatre-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Tagore+Theatre/@30.7330935,76.7870231,17z/data=!3m1!4b1!4m6!3m5!1s0x390fed0f96bfed27:0xe24ba2849c9cfc94!8m2!3d30.7330935!4d76.789598!16s%2Fm%2F0h3lh60?entry=ttu"}
  ],
  5: [
    { name: "Secretariat Building ", about: "A part of the capitol complex, this monument is the largest and tallest of the all the three edifices. Shaped like a concrete-slab, the Secretariat is eight storeys tall. It was built during 1953-59 and has the distinctive brise-soleil-louvered screen of deeply sculptured two-storey porticos in the centre.", timeSpent: "1 hours", imageUrl: "secBuilding.png", linkUrl: "https://www.google.com/search?q=Secretariat+Building%2C+Chandigarh&rlz=1C1ONGR_enIN1061IN1061&oq=secre&gs_lcrp=EgZjaHJvbWUqCAgDEEUYJxg7MgYIABBFGDkyBggBEEUYQDIICAIQRRgnGDsyCAgDEEUYJxg7MhUIBBAuGEMYrwEYxwEYgAQYigUYmAUyCggFEC4YsQMYgAQyCggGEAAYsQMYgAQyDAgHEAAYFBiHAhiABNIBCDM5OTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/search/Secretariat+Building,+Chandigarh/@30.7487379,76.7705976,14z/data=!3m1!4b1?entry=ttu" },
    { name: "Zakir Hussain Rose Garden ", about: "Zakir Hussain Rose Garden, is a botanical garden in Chandigarh, India and spread over 30 acres of land, with 50,000 rose-bushes of 1600 different species.", timeSpent: "2 hours", imageUrl: "zhRose.png", linkUrl: "https://www.tripadvisor.in/ShowUserReviews-g297596-d1575671-r394673300-Chandigarh_Rose_Garden-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Zakir+Hussain+Rose+Garden/@30.7472254,76.7806013,17z/data=!4m10!1m2!2m1!1szakir+hussain+rose+garden!3m6!1s0x390fed75a40e50af:0x759386048e0b7188!8m2!3d30.7470353!4d76.782881!15sChl6YWtpciBodXNzYWluIHJvc2UgZ2FyZGVuWhsiGXpha2lyIGh1c3NhaW4gcm9zZSBnYXJkZW6SAQZnYXJkZW7gAQA!16s%2Fm%2F04ycl9c?entry=ttu"}
  ],
  6: [
    { name: "Secretariat Building ", about: "A part of the capitol complex, this monument is the largest and tallest of the all the three edifices. Shaped like a concrete-slab, the Secretariat is eight storeys tall. It was built during 1953-59 and has the distinctive brise-soleil-louvered screen of deeply sculptured two-storey porticos in the centre.", timeSpent: "1 hours", imageUrl: "secBuilding.png", linkUrl: "https://www.google.com/search?q=Secretariat+Building%2C+Chandigarh&rlz=1C1ONGR_enIN1061IN1061&oq=secre&gs_lcrp=EgZjaHJvbWUqCAgDEEUYJxg7MgYIABBFGDkyBggBEEUYQDIICAIQRRgnGDsyCAgDEEUYJxg7MhUIBBAuGEMYrwEYxwEYgAQYigUYmAUyCggFEC4YsQMYgAQyCggGEAAYsQMYgAQyDAgHEAAYFBiHAhiABNIBCDM5OTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/search/Secretariat+Building,+Chandigarh/@30.7487379,76.7705976,14z/data=!3m1!4b1?entry=ttu" },
    { name: "Zakir Hussain Rose Garden ", about: "Zakir Hussain Rose Garden, is a botanical garden in Chandigarh, India and spread over 30 acres of land, with 50,000 rose-bushes of 1600 different species.", timeSpent: "2 hours", imageUrl: "zhRose.png", linkUrl: "https://www.tripadvisor.in/ShowUserReviews-g297596-d1575671-r394673300-Chandigarh_Rose_Garden-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Zakir+Hussain+Rose+Garden/@30.7472254,76.7806013,17z/data=!4m10!1m2!2m1!1szakir+hussain+rose+garden!3m6!1s0x390fed75a40e50af:0x759386048e0b7188!8m2!3d30.7470353!4d76.782881!15sChl6YWtpciBodXNzYWluIHJvc2UgZ2FyZGVuWhsiGXpha2lyIGh1c3NhaW4gcm9zZSBnYXJkZW6SAQZnYXJkZW7gAQA!16s%2Fm%2F04ycl9c?entry=ttu"},
    { name: "Sector 17 ", about: "Sector 17 is a busy retail and entertainment hub centered on Sector 17 Market, a tree-lined pedestrian plaza with fountains and stores offering global fashion, gifts, and sportswear. Surrounding streets are dotted with international restaurants, ice cream parlors, and traditional sweet shops. Entertainment options include cinemas and bars, while nearby Shanti Kunj Park has a rose garden and lawns for picnics.", timeSpent: "2 hours", imageUrl: "sector17.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d12664267-Reviews-Sector_17_Market-Chandigarh.html",mapURL: "https://www.google.com/maps?sca_esv=74c740cd3a771c52&sca_upv=1&rlz=1C1ONGR_enIN1061IN1061&biw=1536&bih=695&output=search&q=sector+17+chandigarh&source=lnms&entry=mc&ved=1t:200715&ictx=111"}
  ],

  7:[
    { name: "Sukhna Lake", about: "Sukhna Lake in Chandigarh, India, is a reservoir at the foothills of the Himalayas. This 3 km² rain fed lake was created in 1958 by damming the Sukhna Choe, a seasonal stream coming down from the Shivalik Hills. Originally, the seasonal flow entered the lake directly, causing heavy siltation.", timeSpent: "1 hours", imageUrl: "sukhnaLake.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d1204434-Reviews-Sukhna_Lake-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Sukhna+Lake/@30.7420736,76.8008578,14z/data=!3m1!4b1!4m6!3m5!1s0x390fed34138d9147:0x8a7a0db7c410d5a2!8m2!3d30.7421379!4d76.8187557!16zL20vMDd6ZmM3?entry=ttu" },
    { name: "Tagore Theatre ", about: "Tagore Theatre, Chandigarh is a center for cultural performances located in Sector 18, Chandigarh. It was designed by architect Aditya Prakash, who was part of Chandigarh Capital Project Team, headed by Le Corbusier. Aditya Prakash was the principal of Chandigarh College of Architecture", timeSpent: "2 hours", imageUrl: "tagoreTheatre.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d13576385-Reviews-Tagore_Theatre-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Tagore+Theatre/@30.7330935,76.7870231,17z/data=!3m1!4b1!4m6!3m5!1s0x390fed0f96bfed27:0xe24ba2849c9cfc94!8m2!3d30.7330935!4d76.789598!16s%2Fm%2F0h3lh60?entry=ttu"},
    { name: "Secretariat Building ", about: "A part of the capitol complex, this monument is the largest and tallest of the all the three edifices. Shaped like a concrete-slab, the Secretariat is eight storeys tall. It was built during 1953-59 and has the distinctive brise-soleil-louvered screen of deeply sculptured two-storey porticos in the centre.", timeSpent: "1 hours", imageUrl: "secBuilding.png", linkUrl: "https://www.google.com/search?q=Secretariat+Building%2C+Chandigarh&rlz=1C1ONGR_enIN1061IN1061&oq=secre&gs_lcrp=EgZjaHJvbWUqCAgDEEUYJxg7MgYIABBFGDkyBggBEEUYQDIICAIQRRgnGDsyCAgDEEUYJxg7MhUIBBAuGEMYrwEYxwEYgAQYigUYmAUyCggFEC4YsQMYgAQyCggGEAAYsQMYgAQyDAgHEAAYFBiHAhiABNIBCDM5OTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",mapURL: "https://www.google.com/maps/search/Secretariat+Building,+Chandigarh/@30.7487379,76.7705976,14z/data=!3m1!4b1?entry=ttu" },
    { name: "Zakir Hussain Rose Garden ", about: "Zakir Hussain Rose Garden, is a botanical garden in Chandigarh, India and spread over 30 acres of land, with 50,000 rose-bushes of 1600 different species.", timeSpent: "2 hours", imageUrl: "zhRose.png", linkUrl: "https://www.tripadvisor.in/ShowUserReviews-g297596-d1575671-r394673300-Chandigarh_Rose_Garden-Chandigarh.html",mapURL: "https://www.google.com/maps/place/Zakir+Hussain+Rose+Garden/@30.7472254,76.7806013,17z/data=!4m10!1m2!2m1!1szakir+hussain+rose+garden!3m6!1s0x390fed75a40e50af:0x759386048e0b7188!8m2!3d30.7470353!4d76.782881!15sChl6YWtpciBodXNzYWluIHJvc2UgZ2FyZGVuWhsiGXpha2lyIGh1c3NhaW4gcm9zZSBnYXJkZW6SAQZnYXJkZW7gAQA!16s%2Fm%2F04ycl9c?entry=ttu"},
    { name: "Sector 17 ", about: "Sector 17 is a busy retail and entertainment hub centered on Sector 17 Market, a tree-lined pedestrian plaza with fountains and stores offering global fashion, gifts, and sportswear. Surrounding streets are dotted with international restaurants, ice cream parlors, and traditional sweet shops. Entertainment options include cinemas and bars, while nearby Shanti Kunj Park has a rose garden and lawns for picnics.", timeSpent: "2 hours", imageUrl: "sector17.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297596-d12664267-Reviews-Sector_17_Market-Chandigarh.html",mapURL: "https://www.google.com/maps?sca_esv=74c740cd3a771c52&sca_upv=1&rlz=1C1ONGR_enIN1061IN1061&biw=1536&bih=695&output=search&q=sector+17+chandigarh&source=lnms&entry=mc&ved=1t:200715&ictx=111"}
 
  ]
}

const sampleDataGuwa = {
  2:[
    { name: "Maa Kamakhya Temple", about: "The Kamakhya Temple at Nilachal hills in Guwahati, Assam is one of the oldest and most revered centres of Tantric practices, dedicated to the goddess Kamakhya. The temple is the center of the Kulachara Tantra Marga and the site of the Ambubachi Mela, an annual festival that celebrates the menstruation of the goddess", timeSpent: "1 hours", imageUrl: "sukhnaLake.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2097284-Reviews-Kamakhya_Temple-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Maa+Kamakhya+Temple/@26.165828,91.6964542,15z/data=!4m13!1m2!2m1!1skamakhya+temple!3m9!1s0x375a5b04b0f06ef1:0xaaad40304c7d3d1d!5m2!4m1!1i2!8m2!3d26.1664108!4d91.7055031!15sCg9rYW1ha2h5YSB0ZW1wbGVaESIPa2FtYWtoeWEgdGVtcGxlkgEMaGluZHVfdGVtcGxl4AEA!16zL20vMDVsMDJz?entry=ttu" }
  ],
  3:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"}
  ],
  4:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Maa Kamakhya Temple", about: "The Kamakhya Temple at Nilachal hills in Guwahati, Assam is one of the oldest and most revered centres of Tantric practices, dedicated to the goddess Kamakhya. The temple is the center of the Kulachara Tantra Marga and the site of the Ambubachi Mela, an annual festival that celebrates the menstruation of the goddess", timeSpent: "1 hours", imageUrl: "maa.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2097284-Reviews-Kamakhya_Temple-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Maa+Kamakhya+Temple/@26.165828,91.6964542,15z/data=!4m13!1m2!2m1!1skamakhya+temple!3m9!1s0x375a5b04b0f06ef1:0xaaad40304c7d3d1d!5m2!4m1!1i2!8m2!3d26.1664108!4d91.7055031!15sCg9rYW1ha2h5YSB0ZW1wbGVaESIPa2FtYWtoeWEgdGVtcGxlkgEMaGluZHVfdGVtcGxl4AEA!16zL20vMDVsMDJz?entry=ttu" }
  ],
  5:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Saraighat War Memorial Park ", about: "This Park is at Agyathuri on the northern bank of river Brahmaputra. The Park has been constructed at a cost of Rs 65 lakh sanctioned by the state government for preservation and promotion of the memories associated with the Battle of Saraighat which took place in the year 1671 A.D.", timeSpent: "2 hours", imageUrl: "memorial.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/saraighat-war-memorial-park-agyathuri#:~:text=This%20Park%20is%20at%20Agyathuri,in%20the%20year%201671%20A.D.",mapURL: "https://www.google.com/maps/place/Saraighat+War+Memorial+Park/@26.200521,91.6093323,12z/data=!4m10!1m2!2m1!1ssaraighat+war+memorial!3m6!1s0x375a450e9922ef6d:0x85d9731a65409cc4!8m2!3d26.1907863!4d91.6432336!15sChZzYXJhaWdoYXQgd2FyIG1lbW9yaWFskgEEcGFya-ABAA!16s%2Fg%2F11cn0s_5mg?entry=ttu" }

  ],
  6:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Saraighat War Memorial Park ", about: "This Park is at Agyathuri on the northern bank of river Brahmaputra. The Park has been constructed at a cost of Rs 65 lakh sanctioned by the state government for preservation and promotion of the memories associated with the Battle of Saraighat which took place in the year 1671 A.D.", timeSpent: "2 hours", imageUrl: "memorial.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/saraighat-war-memorial-park-agyathuri#:~:text=This%20Park%20is%20at%20Agyathuri,in%20the%20year%201671%20A.D.",mapURL: "https://www.google.com/maps/place/Saraighat+War+Memorial+Park/@26.200521,91.6093323,12z/data=!4m10!1m2!2m1!1ssaraighat+war+memorial!3m6!1s0x375a450e9922ef6d:0x85d9731a65409cc4!8m2!3d26.1907863!4d91.6432336!15sChZzYXJhaWdoYXQgd2FyIG1lbW9yaWFskgEEcGFya-ABAA!16s%2Fg%2F11cn0s_5mg?entry=ttu" },
    { name: "Maa Kamakhya Temple", about: "The Kamakhya Temple at Nilachal hills in Guwahati, Assam is one of the oldest and most revered centres of Tantric practices, dedicated to the goddess Kamakhya. The temple is the center of the Kulachara Tantra Marga and the site of the Ambubachi Mela, an annual festival that celebrates the menstruation of the goddess", timeSpent: "1 hours", imageUrl: "maa.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2097284-Reviews-Kamakhya_Temple-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Maa+Kamakhya+Temple/@26.165828,91.6964542,15z/data=!4m13!1m2!2m1!1skamakhya+temple!3m9!1s0x375a5b04b0f06ef1:0xaaad40304c7d3d1d!5m2!4m1!1i2!8m2!3d26.1664108!4d91.7055031!15sCg9rYW1ha2h5YSB0ZW1wbGVaESIPa2FtYWtoeWEgdGVtcGxlkgEMaGluZHVfdGVtcGxl4AEA!16zL20vMDVsMDJz?entry=ttu" }
  ],
  7:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Saraighat War Memorial Park ", about: "This Park is at Agyathuri on the northern bank of river Brahmaputra. The Park has been constructed at a cost of Rs 65 lakh sanctioned by the state government for preservation and promotion of the memories associated with the Battle of Saraighat which took place in the year 1671 A.D.", timeSpent: "2 hours", imageUrl: "memorial.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/saraighat-war-memorial-park-agyathuri#:~:text=This%20Park%20is%20at%20Agyathuri,in%20the%20year%201671%20A.D.",mapURL: "https://www.google.com/maps/place/Saraighat+War+Memorial+Park/@26.200521,91.6093323,12z/data=!4m10!1m2!2m1!1ssaraighat+war+memorial!3m6!1s0x375a450e9922ef6d:0x85d9731a65409cc4!8m2!3d26.1907863!4d91.6432336!15sChZzYXJhaWdoYXQgd2FyIG1lbW9yaWFskgEEcGFya-ABAA!16s%2Fg%2F11cn0s_5mg?entry=ttu" },
    { name: "Northbrook Gate ", about: "The Northbrook Gate, was constructed to welcome British viceroy Lord Northbrook who visited Guwahati in 1874. The gate was built near Sukreswar Ghat where the viceroy anchored his ship. It is the only monument of its kind in this part of Assam and the lone surviving brick architecture from colonial times.", timeSpent: "2 hours", imageUrl: "north.png", linkUrl:"",mapURL: "https://www.google.com/maps?sca_esv=d7773eb477db942c&sca_upv=1&rlz=1C1ONGR_enIN1061IN1061&biw=1536&bih=695&output=search&q=north+brook+gate&source=lnms&entry=mc&ved=1t:200715&ictx=111"}
  ],
  8:[
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "2 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Saraighat War Memorial Park ", about: "This Park is at Agyathuri on the northern bank of river Brahmaputra. The Park has been constructed at a cost of Rs 65 lakh sanctioned by the state government for preservation and promotion of the memories associated with the Battle of Saraighat which took place in the year 1671 A.D.", timeSpent: "2 hours", imageUrl: "memorial.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/saraighat-war-memorial-park-agyathuri#:~:text=This%20Park%20is%20at%20Agyathuri,in%20the%20year%201671%20A.D.",mapURL: "https://www.google.com/maps/place/Saraighat+War+Memorial+Park/@26.200521,91.6093323,12z/data=!4m10!1m2!2m1!1ssaraighat+war+memorial!3m6!1s0x375a450e9922ef6d:0x85d9731a65409cc4!8m2!3d26.1907863!4d91.6432336!15sChZzYXJhaWdoYXQgd2FyIG1lbW9yaWFskgEEcGFya-ABAA!16s%2Fg%2F11cn0s_5mg?entry=ttu" },
    { name: "Northbrook Gate ", about: "The Northbrook Gate, was constructed to welcome British viceroy Lord Northbrook who visited Guwahati in 1874. The gate was built near Sukreswar Ghat where the viceroy anchored his ship. It is the only monument of its kind in this part of Assam and the lone surviving brick architecture from colonial times.", timeSpent: "2 hours", imageUrl: "north.png", linkUrl:"",mapURL: "https://www.google.com/maps?sca_esv=d7773eb477db942c&sca_upv=1&rlz=1C1ONGR_enIN1061IN1061&biw=1536&bih=695&output=search&q=north+brook+gate&source=lnms&entry=mc&ved=1t:200715&ictx=111"},
    { name: "Assam State Museum ", about: "The Assam State Museum, previously Assam Provincial Museum, is located in the southern end of Dighalipukhuri tank which is in the heart of Guwahati city, Assam. The Museum was established by the Kamarupa Anusandhan Samiti in 1940. The late Kanaklal Barua was the founder and president.", timeSpent: "1 hours", imageUrl: "museum.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2693640-Reviews-Assam_Rajyik_State_Museum-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Assam+State+Museum/@26.185175,91.749502,17z/data=!3m1!4b1!4m6!3m5!1s0x375a5a27c47f6c07:0xe07929f42278107f!8m2!3d26.185175!4d91.7520769!16s%2Fm%2F026hlsb?entry=ttu"}
  ],
  9:[
    { name: "Maa Kamakhya Temple", about: "The Kamakhya Temple at Nilachal hills in Guwahati, Assam is one of the oldest and most revered centres of Tantric practices, dedicated to the goddess Kamakhya. The temple is the center of the Kulachara Tantra Marga and the site of the Ambubachi Mela, an annual festival that celebrates the menstruation of the goddess", timeSpent: "1 hours", imageUrl: "maa.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2097284-Reviews-Kamakhya_Temple-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Maa+Kamakhya+Temple/@26.165828,91.6964542,15z/data=!4m13!1m2!2m1!1skamakhya+temple!3m9!1s0x375a5b04b0f06ef1:0xaaad40304c7d3d1d!5m2!4m1!1i2!8m2!3d26.1664108!4d91.7055031!15sCg9rYW1ha2h5YSB0ZW1wbGVaESIPa2FtYWtoeWEgdGVtcGxlkgEMaGluZHVfdGVtcGxl4AEA!16zL20vMDVsMDJz?entry=ttu" },
    { name: "Atal Udyan ", about: "Atal Udyan is an urban park situated at Adabari Tiniali in the Maligaon area of Guwahati, India.", timeSpent: "1 hours", imageUrl: "atal.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/atal-udyan-at-adabari-tiniali-0",mapURL: "https://www.google.com/maps/search/atal+udyan/@12.9892352,80.2357248,124407a,13.1y/data=!3m1!4b1?entry=ttu"},
    { name: "Saraighat War Memorial Park ", about: "This Park is at Agyathuri on the northern bank of river Brahmaputra. The Park has been constructed at a cost of Rs 65 lakh sanctioned by the state government for preservation and promotion of the memories associated with the Battle of Saraighat which took place in the year 1671 A.D.", timeSpent: "2 hours", imageUrl: "memorial.png", linkUrl: "https://gmda.assam.gov.in/portlet-sub-innerpage/saraighat-war-memorial-park-agyathuri#:~:text=This%20Park%20is%20at%20Agyathuri,in%20the%20year%201671%20A.D.",mapURL: "https://www.google.com/maps/place/Saraighat+War+Memorial+Park/@26.200521,91.6093323,12z/data=!4m10!1m2!2m1!1ssaraighat+war+memorial!3m6!1s0x375a450e9922ef6d:0x85d9731a65409cc4!8m2!3d26.1907863!4d91.6432336!15sChZzYXJhaWdoYXQgd2FyIG1lbW9yaWFskgEEcGFya-ABAA!16s%2Fg%2F11cn0s_5mg?entry=ttu" },
    { name: "Northbrook Gate ", about: "The Northbrook Gate, was constructed to welcome British viceroy Lord Northbrook who visited Guwahati in 1874. The gate was built near Sukreswar Ghat where the viceroy anchored his ship. It is the only monument of its kind in this part of Assam and the lone surviving brick architecture from colonial times.", timeSpent: "2 hours", imageUrl: "north.png", linkUrl:"",mapURL: "https://www.google.com/maps?sca_esv=d7773eb477db942c&sca_upv=1&rlz=1C1ONGR_enIN1061IN1061&biw=1536&bih=695&output=search&q=north+brook+gate&source=lnms&entry=mc&ved=1t:200715&ictx=111"},
    { name: "Assam State Museum ", about: "The Assam State Museum, previously Assam Provincial Museum, is located in the southern end of Dighalipukhuri tank which is in the heart of Guwahati city, Assam. The Museum was established by the Kamarupa Anusandhan Samiti in 1940. The late Kanaklal Barua was the founder and president.", timeSpent: "1 hours", imageUrl: "museum.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g503692-d2693640-Reviews-Assam_Rajyik_State_Museum-Guwahati_Kamrup_Metropolitan_District_Assam.html",mapURL: "https://www.google.com/maps/place/Assam+State+Museum/@26.185175,91.749502,17z/data=!3m1!4b1!4m6!3m5!1s0x375a5a27c47f6c07:0xe07929f42278107f!8m2!3d26.185175!4d91.7520769!16s%2Fm%2F026hlsb?entry=ttu"}
  ]
}

const sampleDataTri = {
  2: [
    { name: "padmanabhaswamy temple", about: "The Padmanabhaswamy Temple is a Hindu temple dedicated to Vishnu in Thiruvananthapuram, the capital of the state of Kerala, India. It is one of the 108 Divya Desams which are considered the sacred abodes of Vishnu in the Sri Vaishnava tradition.", timeSpent: "2 hours", imageUrl: "pad.png", linkUrl: "https://www.tripadvisor.in/Attraction_Review-g297637-d478102-Reviews-Sree_Padmanabhaswamy_Temple-Thiruvananthapuram_Trivandrum_Thiruvananthapuram_Distr.html",mapURL: "https://www.google.com/maps/place/Sree+Padmanabhaswamy+Temple/@8.4836442,76.9416352,17z/data=!4m10!1m2!2m1!1spadmanabhaswamy+temple!3m6!1s0x3b05bb09b7e81d35:0x1d2fedb7213a1ef7!8m2!3d8.4827779!4d76.9435906!15sChZwYWRtYW5hYmhhc3dhbXkgdGVtcGxlWhgiFnBhZG1hbmFiaGFzd2FteSB0ZW1wbGWSAQxoaW5kdV90ZW1wbGWaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTmtOMHhVVGpWUlJSQULgAQA!16zL20vMDdmMGt0?entry=ttu"}
  ]
}




const showPos = (position) = () => {
  console.log(position)
}
const getLocation = () => {
  navigator.geolocation.getCurrentPosition(showPos);
}

getLocation()

const options = {
  enableHighAccuracy: true,
  timeout: 5000,
  maximumAge: 0
};

const lati = document.getElementById("lat");
const longi = document.getElementById("long");

function success(pos) {
  const crd = pos.coords;
  window.alert(`Current location, Latitude: ${crd.latitude}, Longitude : ${crd.longitude}`);
  lati.innerText = crd.latitude;
  longi.innerText = crd.longitude;
}
function error(err) {
    console.warn(`ERROR(${err.code}): ${err.message}`);
    addLatLong();
}


navigator.geolocation.getCurrentPosition(success, error, options);

// Function to display places
function displayPlaces(places) {
  console.log("Places:", places); // Log places to inspect its value
  const placesList = document.getElementById("placesList");
  
  
  places.forEach((place, index) => {
    const placeBlock = document.createElement("div");
    placeBlock.classList.add("place-block");
    placeBlock.innerHTML = `
      <a href="${place.mapURL}" class="place-link" target="_blank">
        <img src="${place.imageUrl}" alt="${place.name}" class="place-image">
      </a>
      <div class="place-info">
        <h2><a href="${place.linkUrl}" target="_blank">${place.name}</a></h2>
        <p><strong>About:</strong> ${place.about}</p>
        <p><strong>Time Spent:</strong> ${place.timeSpent}</p>
      </div>
    `;
    placesList.appendChild(placeBlock);

    if (index !== places.length - 1) {
      const arrow = document.createElement("div");
      arrow.classList.add("arrow", "left-arrow");
      placesList.appendChild(arrow);
    }
  });
}

const findBtn = document.getElementById("findBtn");
findBtn.addEventListener("click", function() {   
  const place = document.getElementById("cityName").value.toLowerCase(); 
  const time = parseInt(document.getElementById("time").value);
  let data;
  
  if (place === "bengaluru") {
    console.log("reached")
    if (time >= 0 && time <= 12)
      data = sampleDataBang[time.toString()];
    else
      data = sampleDataBang["13"];
  }
  else if (place === "chandigarh") {
    console.log("reached")
    if(time>=2 && time<=6)
      data = sampleDataChand[time.toString()];
    else
      data = sampleDataChand["7"];
  }
  else if(place==="guwahati")
  {
    if(time>=2 && time<=8)
      data = sampleDataGuwa[time.toString()];
    else
      data = sampleDataGuwa["9"];
  }
  else if(place === "thiruvananthapuram")
    {
      data=sampleDataTri["2"]
    }
  console.log("reached")
  console.log("Data: ", data); 
  displayPlaces(data);
  
});






